#include<map>
#include<cmath>
#include<queue>
#include<stack>
#include<cstdio>
#include<cstring>
#include<iostream>
#include<algorithm>

using namespace std;
string ans[10][10] = {
    {"-1", "RL", "-1", "-1", "-1", "-1", "-1", "-1", "-1", "-1"},
    {"DU", "DRUL", "DRRULL", "DRRRULLL", "DRRRRULLLL", "DRRRRRULLLLL", "DRRRRRRULLLLLL", "DRRRRRRRULLLLLLL", "DRRRRRRRRULLLLLLLL", "DRRRRRRRRRULLLLLLLLL"},
    {"-1", "DDRUUL", "-1", "DDRURDRUULLL", "-1", "DDRURDRURDRUULLLLL", "-1", "DDRURDRURDRURDRUULLLLLLL", "-1", "DDRURDRURDRURDRURDRUULLLLLLLLL"},
    {"-1", "DDDRUUUL", "DDDRRULURULL", "DDDRUURDDRUUULLL", "DDDRUURDDRRULURULLLL", "DDDRUURDDRUURDDRUUULLLLL", "DDDRUURDDRUURDDRRULURULLLLLL", "DDDRUURDDRUURDDRUURDDRUUULLLLLLL", "DDDRUURDDRUURDDRUURDDRRULURULLLLLLLL", "DDDRUURDDRUURDDRUURDDRUURDDRUUULLLLLLLLL"},
    {"-1", "DDDDRUUUUL", "-1", "DDDDRUUURDDDRUUUULLL", "-1", "DDDDRUUURDDDRUUURDDDRUUUULLLLL", "-1", "DDDDRUUURDDDRUUURDDDRUUURDDDRUUUULLLLLLL", "-1", "DDDDRUUURDDDRUUURDDDRUUURDDDRUUURDDDRUUUULLLLLLLLL"},
    {"-1", "DDDDDRUUUUUL", "DDDDDRRULURULURULL", "DDDDDRUUUURDDDDRUUUUULLL", "DDDDDRUUUURDDDDRRULURULURULLLL", "DDDDDRUUUURDDDDRUUUURDDDDRUUUUULLLLL", "DDDDDRUUUURDDDDRUUUURDDDDRRULURULURULLLLLL", "DDDDDRUUUURDDDDRUUUURDDDDRUUUURDDDDRUUUUULLLLLLL", "DDDDDRUUUURDDDDRUUUURDDDDRUUUURDDDDRRULURULURULLLLLLLL", "DDDDDRUUUURDDDDRUUUURDDDDRUUUURDDDDRUUUURDDDDRUUUUULLLLLLLLL"},
    {"-1", "DDDDDDRUUUUUUL", "-1", "DDDDDDRUUUUURDDDDDRUUUUUULLL", "-1", "DDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUUULLLLL", "-1", "DDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUUULLLLLLL", "-1", "DDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUURDDDDDRUUUUUULLLLLLLLL"},
    {"-1", "DDDDDDDRUUUUUUUL", "DDDDDDDRRULURULURULURULL", "DDDDDDDRUUUUUURDDDDDDRUUUUUUULLL", "DDDDDDDRUUUUUURDDDDDDRRULURULURULURULLLL", "DDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUUULLLLL", "DDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRRULURULURULURULLLLLL", "DDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUUULLLLLLL", "DDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRRULURULURULURULLLLLLLL", "DDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUURDDDDDDRUUUUUUULLLLLLLLL"},
    {"-1", "DDDDDDDDRUUUUUUUUL", "-1", "DDDDDDDDRUUUUUUURDDDDDDDRUUUUUUUULLL", "-1", "DDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUUULLLLL", "-1", "DDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUUULLLLLLL", "-1", "DDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUURDDDDDDDRUUUUUUUULLLLLLLLL"},
    {"-1", "DDDDDDDDDRUUUUUUUUUL", "DDDDDDDDDRRULURULURULURULURULL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUUULLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRRULURULURULURULURULLLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUUULLLLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRRULURULURULURULURULLLLLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUUULLLLLLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRRULURULURULURULURULLLLLLLL", "DDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUURDDDDDDDDRUUUUUUUUULLLLLLLLL"}
};

int main(){
    int n, m;
    cin>>n>>m;
    cout<<ans[n-1][m-1]<<endl;
    return 0;
}